### ISSUE TITLE
eror when install

### ISSUE THREAD

**Issue by pengengantibaju** [Hanivan/Samehadaku-CLI#2]
![image](https://user-images.githubusercontent.com/92777707/167802387-8ef20ca4-cb71-4d6e-b300-ae325662c714.png)

**Comment by Hanivan** [comment]
@pengengantibaju This application only supports Linux Operating System...  ٩(｡•́‿•̀｡)۶

**Comment by Hanivan** [comment]
![2022-05-11-160648_2646x768_scrot](https://user-images.githubusercontent.com/66857547/167813146-af7d9af2-984a-4672-b38c-e6bd182f03c5.png)
@pengengantibaju here's the preview. If you are curious about my pc specs. [see here](https://github.com/Hanivan/dotfiles)
